version: '3'
services:
  smartmetserver:
    image: fmidev/smartmetserver:latest
    container_name: smartmetserver
    labels:
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.co.meteo.fi`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8080"
    volumes:
      - /smartmet/cnf/server:/etc/smartmet
      - /smartmet/share/wms/customers/ideam:/smartmet/share/wms/customers/ideam
      - /smartmet/data:/smartmet/data
    networks:
      - traefik-network
    restart: unless-stopped
  smartmet-server-db:
    image: smartmet-server-db
    container_name: smartmet-server-db
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    ports:
     - "5432:5432"
    volumes:
      - /smartmet/data/db:/var/lib/postgresql/data
    networks:
      traefik-network:
volumes:
  smartmetserver-storage-cnf:
    
networks:
    traefik-network:
      external: true
